leonardo_module_folio/models.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.db import models

from django.utils.translation import ugettext_lazy as _

from feincms.module.page.extensions.navigation import NavigationExtension, PagePretender
from feincms.content.application.models import reverse

from feincms.translations import TranslatedObjectMixin, Translation, TranslatedObjectManager
from mptt.models import MPTTModel

from leonardo.module.media.models import Folder, File, Image


class Category(MPTTModel, TranslatedObjectMixin):

    """
    An encapsulation of a portfolio category.
    """
    ordering = models.SmallIntegerField()
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children')
    logo = models.ForeignKey(Image, blank=True, null=True, verbose_name=_("logo"))
    active = models.BooleanField(default=True)

    objects = TranslatedObjectManager()

    class MPTTMeta:
        level_attr = 'mptt_level'
        order_insertion_by = ['ordering', ]

    class Meta:
        ordering = ('ordering',)
        verbose_name = _('portfolio category')
        verbose_name_plural = _('portfolio categories')
        unique_together = (("ordering", "parent"),)

    def __unicode__(self):
        trans = None

        if hasattr(self, "preferred_translation"):
            trans = getattr(self, "preferred_translation", u"")
        else:
            try:
                trans = unicode(self.translation)
            except models.ObjectDoesNotExist:
                pass
            except AttributeError:
                pass

        if trans:
            return trans
        else:
            return u"[ no name ]"


class CategoryTranslation(Translation(Category)):

    """
    Translations for category.
    """
    title = models.CharField(max_length=255, verbose_name=_("title"))
    slug = models.SlugField(_('slug'),)
    summary = models.CharField(_('summary'), max_length=250, blank=True)
    description = models.TextField(_('description'), blank=True, null=True)

    class Meta:
        verbose_name = _('category text')
        verbose_name_plural = _('category texts')

    def __unicode__(self):
        return self.title


class Service(models.Model, TranslatedObjectMixin):

    """
    An encapsulation of a service.
    """
    ordering = models.IntegerField(blank=True, null=True)
    logo = models.ForeignKey(Image, blank=True, null=True, verbose_name=_("logo"))
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('ordering',)
        verbose_name = _('service')
        verbose_name_plural = _('services')

    objects = TranslatedObjectManager()

    def __unicode__(self):
        trans = None

        if hasattr(self, "preferred_translation"):
            trans = getattr(self, "preferred_translation", u"")
        else:
            try:
                trans = unicode(self.translation)
            except models.ObjectDoesNotExist:
                pass
            except AttributeError:
                pass

        if trans:
            return trans
        else:
            return u"[ no name ]"


class ServiceTranslation(Translation(Service)):

    """
    Translations for service.
    """
    title = models.CharField(max_length=255, verbose_name=_("title"))
    slug = models.SlugField(_('slug'),)
    summary = models.CharField(_('summary'), max_length=250, blank=True)
    description = models.TextField(_('description'), blank=True, null=True)

    class Meta:
        verbose_name = _('service translation')
        verbose_name_plural = _('service translations')

    def __unicode__(self):
        return self.title


class Client(models.Model, TranslatedObjectMixin):

    """
    A project's client.
    """
    logo = models.ForeignKey(Image, blank=True, null=True, verbose_name=_("logo"))
    ordering = models.IntegerField(blank=True, null=True, verbose_name=_("ordering"))
    active = models.BooleanField(default=True, verbose_name=_("active"))

    class Meta:
        ordering = ('ordering',)
        verbose_name = _('client')
        verbose_name_plural = _('clients')

    objects = TranslatedObjectManager()

    def __unicode__(self):
        trans = None

        if hasattr(self, "preferred_translation"):
            trans = getattr(self, "preferred_translation", u"")
        else:
            try:
                trans = unicode(self.translation)
            except models.ObjectDoesNotExist:
                pass
            except AttributeError:
                pass

        if trans:
            return trans
        else:
            return u"[ no name ]"


class ClientTranslation(Translation(Client)):

    """
    Translations for client.
    """
    title = models.CharField(max_length=255, verbose_name=_("title"))
    slug = models.SlugField(_('slug'),)
    summary = models.CharField(_('summary'), max_length=250, blank=True)
    description = models.TextField(_('description'), blank=True, null=True)

    class Meta:
        verbose_name = _('client translation')
        verbose_name_plural = _('client translations')

    def __unicode__(self):
        return self.title


class Project(models.Model, TranslatedObjectMixin):

    """
    An encapsualtion of a project.
    """
    categories = models.ManyToManyField(Category, verbose_name=_("categories"))
    client = models.ForeignKey(Client, verbose_name=_("client"), blank=True, null=True)
    files = models.ManyToManyField(
        File, blank=True, verbose_name=_("files"), through='ProjectFile')
    media_category = models.ForeignKey(
        Folder, blank=True, null=True, verbose_name=_("media category"))
    services = models.ManyToManyField(
        Service, blank=True, verbose_name=_("services"))
    created = models.DateField(blank=True, null=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    objects = TranslatedObjectManager()

    class Meta:
        ordering = ('-created',)
        verbose_name = _('project')
        verbose_name_plural = _('projects')

    def get_main_file(self):
        qs = ProjectFile.objects.filter(featured=True, project=self)
        if qs.count() > 0:
            return qs[0]
        else:
            return None

    def get_other_files(self):
        qs = self.files.all()
        if qs.count() > 1:
            return qs[1:qs.count()]
        else:
            return None

    def __unicode__(self):
        trans = None

        if hasattr(self, "preferred_translation"):
            trans = getattr(self, "preferred_translation", u"")
        else:
            try:
                trans = unicode(self.translation)
            except models.ObjectDoesNotExist:
                pass
            except AttributeError, e:
                pass

        if trans:
            return trans
        else:
            return u"[ no name ]"


class ProjectTranslation(Translation(Project)):

    """
    Translations for project.
    """
    title = models.CharField(max_length=255, verbose_name=_("title"))
    slug = models.SlugField(_('slug'),)
    summary = models.CharField(_('summary'), max_length=250, blank=True)
    description = models.TextField(_('description'), blank=True, null=True)

    class Meta:
        verbose_name = _('project text')
        verbose_name_plural = _('project texts')

    def __unicode__(self):
        return self.title

VALIDATION_CHOICES = (
    ('webcms.utils.validation.simple', _('One or more characters')),
    ('webcms.utils.validation.integer', _('Integer number')),
    ('webcms.utils.validation.yesno', _('Yes or No')),
    ('webcms.utils.validation.decimal', _('Decimal number')),
)


class AttributeOption(models.Model, TranslatedObjectMixin):

    """
    Allows arbitrary name/value pairs to be attached to a project.
    """
    ordering = models.IntegerField(_("sort order"), default=1)
    validation = models.CharField(
        _("field validations"), choices=VALIDATION_CHOICES, max_length=100)
    error_message = models.CharField(
        _("error message"), default=_("Invalid entry"), max_length=100)

    objects = TranslatedObjectManager()

    class Meta:
        ordering = ('ordering',)
        verbose_name = _('attribute option')
        verbose_name_plural = _('attribute options')

    def __unicode__(self):
        trans = None

        if hasattr(self, "preferred_translation"):
            trans = getattr(self, "preferred_translation", u"")
        else:
            try:
                trans = unicode(self.translation)
            except models.ObjectDoesNotExist:
                pass
            except AttributeError, e:
                pass

        if trans:
            return trans
        else:
            return u"[ no name ]"


class AttributeOptionTranslation(Translation(AttributeOption)):

    """
    Translations for attribute option.
    """
    title = models.CharField(max_length=255, verbose_name=_("title"))
    summary = models.CharField(_('summary'), max_length=250, blank=True)

    class Meta:
        verbose_name = _('attribute option translation')
        verbose_name_plural = _('attribute option translations')

    def __unicode__(self):
        return self.title


class ProjectAttribute(models.Model):

    """
    Allows arbitrary name/value pairs (as strings) to be attached to a project.
    """
    project = models.ForeignKey(Project)
    languagecode = models.CharField(
        _('language'), max_length=10, choices=settings.LANGUAGES, null=True, blank=True)
    option = models.ForeignKey(AttributeOption)
    value = models.CharField(_("Value"), max_length=255)

    def _name(self):
        return self.option.translation.title
    name = property(_name)

    def _description(self):
        return self.option.description
    description = property(_description)

    class Meta:
        verbose_name = _("Project attribute")
        verbose_name_plural = _("Project attributes")
        ordering = ('option__ordering',)

    def __unicode__(self):

leonardo_module_folio/templates/folio/category_detail.html
{% extends widget.get_base_template %}

{% load i18n %}
{% load leonardo_tags leonardo_page_tags thumbnail %}

{% block content %}

<style type="text/css">
.project-image {
    width: 100%
}

.nav-pills li a {
    color: #333333;
}

.nav-stacked.second-nav {
    margin-left: 32px;
    border-left: 1px solid #333333;
}

.bold {
    font-weight: bold;
}

.object-text {
    text-align: center;
}

.object-text a {
    color: #333333;
}
</style>


<div class="row">
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked first-nav">
        {% for category in category_list %}
            <li class="{% if category.translation.slug in request.path %}bold{% endif %}"><a href="{% app_reverse 'folio_category_detail' 'leonardo_module_folio.apps.folio' category_slug=category.translation.slug %}">{{ category.translation.title }}</a></li>
            {% if category.translation.slug in request.path %}
            <ul class="nav nav-pills nav-stacked second-nav">
            {% for sub_project in category.project_set.all %}
                <li><a href="{% app_reverse 'folio_project_detail' 'leonardo_module_folio.apps.folio' category_slug=sub_project.categories.first.translation.slug project_slug=sub_project.translation.slug %}" title="{{ sub_project }}">{{ sub_project }}</a></li>
            {% endfor %}
            </ul>
            {% endif %}
        {% endfor %}
        </ul>
    </div>
    <div class="col-md-9">
        <h1>{{ object.translation.title }}</h1>
        <div class="object-grid">
            {% for object in object.project_set.all %}
            <div class="col-md-3">
                <div class="folio_item object-cell">
                    <a class="object-image" href="{% app_reverse 'folio_project_detail' 'leonardo_module_folio.apps.folio' category_slug=object.categories.first.translation.slug project_slug=object.translation.slug %}" title="{{ object }}">
                        {% if object.media_category %}
                        {% if object.media_category.get_featured_image.file %}
                        {% thumbnail object.media_category.get_featured_image.file "250x250" crop="center" format="PNG" as image %}
                        <img class="project-image" alt="{{ object }}" src="{{ image.url }}" />
                        {% endthumbnail %}
                        {% endif %}
                        {% endif %}
                    </a>
                    <div class="object-text">
                        <p><a href="{% app_reverse 'folio_project_detail' 'leonardo_module_folio.apps.folio' category_slug=object.categories.first.translation.slug project_slug=object.translation.slug %}" title="{{ object }}">{{ object }}</a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

leonardo_module_folio/templates/folio/project_detail.html
{% extends widget.get_base_template %}

{% load i18n %}
{% load leonardo_tags leonardo_page_tags thumbnail %}

{% block content %}

<style type="text/css">
.project-image {
    width: 70%;
    margin-top: 10px;
}

.nav-pills li a {
    color: #333333;
}

.nav-stacked.second-nav {
    margin-left: 32px;
    border-left: 1px solid #333333;
}

.bold {
    font-weight: bold;
}
.object-text {
    text-align: center;
}

.object-text a {
    color: #333333;
}
</style>

<div class="object-detail">
    <div class="row">
        <div class="col-md-3">
            <ul class="nav nav-pills nav-stacked first-nav">
            {% for category in category_list %}
                <li class="{% if category.translation.slug in request.path %}bold{% endif %}"><a href="{% app_reverse 'folio_category_detail' 'leonardo_module_folio.apps.folio' category_slug=category.translation.slug %}">{{ category.translation.title }}</a></li>
                {% if category.translation.slug in request.path %}
                <ul class="nav nav-pills nav-stacked second-nav">
                {% for sub_project in category.project_set.all %}
                    <li class="{% if sub_project.translation.slug in request.path %}bold{% endif %}"><a href="{% app_reverse 'folio_project_detail' 'leonardo_module_folio.apps.folio' category_slug=sub_project.categories.first.translation.slug project_slug=sub_project.translation.slug %}" title="{{ sub_project }}">{{ sub_project }}</a></li>
                {% endfor %}
                </ul>
                {% endif %}
            {% endfor %}
            </ul>
        </div>
        <div class="col-md-9">
            <h1>{{ object.translation.title }}</h1>
            {% for file in object.files.all %}
            <div class="object-image">
                {% thumbnail file.file "720x480" format="PNG" as image %}
                <a href="" rel="clearbox[image]"><img src="{{ image.url }}" /></a>
                {% endthumbnail %}
            </div>
            {% endfor %}

            {% for file in object.media_category.media_file_files.all %}
            <div class="object-image">
                {% thumbnail file.file "720x480" format="PNG" as image %}
                <a href="" rel="clearbox[image]"><img class="project-image" src="{{ image.url }}" /></a>
                {% endthumbnail %}
            </div>
            {% endfor %}

            <div class="object-attributes">
            {% for attribute in object.projectattribute_set.all %}
                <h4>{{ attribute.option.translation.title }}</h4>
                <p>{{ attribute.value }}</p>
            {% endfor %}
            </div>

            {% if object.translation.description %}
            <div class="object-text">
                {{ object.translation.description|safe }}
            </div>
            {% endif %}
        </div>
    </div>
    
</div>

{% endblock %}

leonardo_module_folio/templates/folio/project_list.html
{% extends widget.get_base_template %}

{% load i18n %}
{% load leonardo_tags leonardo_page_tags thumbnail %}

{% block content %}

<style type="text/css">
.project-image {
    width: 100%
}

.nav-pills li a {
    color: #333333;
}

.object-text {
    text-align: center;
}

.object-text a {
    color: #333333;
}
</style>

<div class="row">
    <div class="col-md-3">
        <ul class="nav nav-pills nav-stacked first-nav">
        {% for category in category_list %}
            <li><a href="{% app_reverse 'folio_category_detail' 'leonardo_module_folio.apps.folio' category_slug=category.translation.slug %}">{{ category.translation.title }}</a></li>
        {% endfor %}
        </ul>
    </div>
    <div class="col-md-9">
        <h1>{% trans "All projects" %}</h1>
        <div class="object-grid">
            {% for object in object_list %}
            <div class="col-md-3">
                <div class="folio_item object-cell">
                    <a class="object-image" href="{% app_reverse 'folio_project_detail' 'leonardo_module_folio.apps.folio' category_slug=object.categories.first.translation.slug project_slug=object.translation.slug %}" title="{{ object }}">
                        {% if object.media_category %}
                        {% if object.media_category.get_featured_image.file %}
                        {% thumbnail object.media_category.get_featured_image.file "250x250" crop="center" format="PNG" as image %}
                        <img class="project-image" alt="{{ object }}" src="{{ image.url }}" />
                        {% endthumbnail %}
                        {% endif %}
                        {% endif %}
                    </a>
                    <div class="object-text">
                        <p><a href="{% app_reverse 'folio_project_detail' 'leonardo_module_folio.apps.folio' category_slug=object.categories.first.translation.slug project_slug=object.translation.slug %}" title="{{ object }}">{{ object }}</a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}